// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IConfigSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IConfigSystem {
  function app__configGame(
    uint256 gameId,
    uint256 xSize,
    uint256 ySize,
    uint256 baseRate,
    int256 bonusSame,
    int256 bonusEnemy,
    int256 bonusVictim,
    uint256 pricePerTile
  ) external;

  function app__withdraw() external;
}
