// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GameProperties, GamePropertiesData } from "./tables/GameProperties.sol";
import { Tiles, TilesData } from "./tables/Tiles.sol";
import { Owners, OwnersData } from "./tables/Owners.sol";
import { Counter } from "./tables/Counter.sol";
